#!/bin/bash

tipo_instalacao=""
DEST_DIR="$HOME/.local/src"
PACOTES_BASE="libxft libxinerama lightdm-gtk-greeter"
PACOTES_EXTRA="ttf-jetbrains-mono ttf-nerd-fonts-symbols noto-fonts-emoji pipewire brightnessctl picom xwallpaper scrot xclip xdotool"
PACOTES_INSTALADOS=""

REPOS=(
	"http://git.suckless.org/dwm"
	"http://git.suckless.org/st"
	"http://git.suckless.org/dmenu"
	"http://git.suckless.org/slstatus"
)

REPOS_CUSTOM=(
    "https://github.com/jorlandosp/dwm"
    "https://github.com/jorlandosp/st"
    "http://git.suckless.org/dmenu"
    "http://git.suckless.org/scroll"
    "https://github.com/jorlandosp/slstatus"
    )

ler_entrada_ins() {
    while true; do
        read -p "Que tipo de instalação deseja realizar? / (Digite C para Customizar e P para padrão)" tipo_instalacao
        if [[ "${tipo_instalacao,,}" == "c" ]]; then
            echo "Instalação customizada"
            pacotes_avulsos
            criar_dir
            instalar_pacotes "$PACOTES_BASE $PACOTES_EXTRA"
            clonagem_repos "${REPOS_CUSTOM[@]}"
            cop_conf
            cop_extra
            selec_greeter
            instalar_yay
            instalar_pywal
            habilitar_iniciar_dm
            resumo_instalacao
            break
        elif [ $tipo_instalacao == p ]; then
            echo "Instalação padrão"
            pacotes_avulsos
            criar_dir
            instalar_pacotes "$PACOTES_BASE"
            clonagem_repos "${REPOS[@]}"
            cop_conf
            selec_greeter
            habilitar_iniciar_dm
            resumo_instalacao
            break
        else	
            echo "Tipo inválido"
        fi
    done
}

instalar_pacotes(){
    pacotes="$1"
    echo "Atualizando pacotes"
    sudo pacman -Suy
    echo "Instalando $pacotes"
    sudo pacman -S --noconfirm $pacotes
    PACOTES_INSTALADOS="$PACOTES_INSTALADOS $pacotes"
}

clonagem_repos() {
    repo_usar=("$@")
	for repo in "${repo_usar[@]}"; do
	repo_name=$(basename -s .git "$repo")
	git clone "$repo" "$DEST_DIR/$repo_name"

	cd "$DEST_DIR/$repo_name" || { echo "Falha ao acessar o diretório $repo_name"; exit 1; }
	sudo make clean install || { echo "Flaha ao installar o $repo_name"; exit 1; }
	cd - > /dev/null
done
}

instalar_yay() {
    git clone https://aur.archlinux.org/yay.git "$DEST_DIR/yay"
    cd "$DEST_DIR/yay" || exit 1
    makepkg -si
    PACOTES_INSTALADOS="$PACOTES_INSTALADOS yay"
}

instalar_pywal() {
    yay -S --noconfirm pywal
    PACOTES_INSTALADOS="$PACOTES_INSTALADOS pywal"
}

criar_dir() {
	mkdir -p $HOME/.local/{src,bin,share}
	sudo mkdir -p /usr/share/xsessions/
}

u
cop_conf() {
	sudo cp dwm.desktop /usr/share/xsessions/ 
}

cop_extra() {
    mkdir -p $HOME/.config
    cp styled $HOME/.local/bin/
    cp picom.conf $HOME/.config/
    cp xbindkeys $HOME/.xbindkeys
    cp xprofile $HOME/.xprofile
    cp -R Wallpapers $HOME/
}

selec_greeter() {
	echo "greeter-session=lightdm-gtk-greeter" | sudo tee -a /etc/lightdm/lightdm.conf
}

habilitar_iniciar_dm() {
	sudo systemctl enable lightdm
    sudo systemctl start lightdm
}

pacotes_avulsos() {
    read -p "Deseja instalar pacotes avulsos? (Digite os nomes separados por espaço ou deixe vazio para pular): " pacotes_extras
    if [[ -n "$pacotes_extras" ]]; then
        instalar_pacotes "$pacotes_extras"
    fi
}


resumo_instalacao() {
    tipo="$1"
    echo ""
    echo "===== Resumo da Instalação ====="
    echo "Tipo de instalação: $tipo"
    echo "Pacotes instalados: $PACOTES_INSTALADOS"
    echo "================================"

        # Salvando no arquivo de resumo
    echo "===== Resumo da Instalação =====" > "$RESUMO_ARQUIVO"
    echo "Tipo de instalação: $tipo" >> "$RESUMO_ARQUIVO"
    echo "Pacotes instalados: $PACOTES_INSTALADOS" >> "$RESUMO_ARQUIVO"
    echo "================================" >> "$RESUMO_ARQUIVO"
    echo "Resumo salvo em: $RESUMO_ARQUIVO"
}


ler_entrada_ins

